# for local development

version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=local
      - IS_LOCAL=true
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - DYNAMODB_TABLE_NAME=ViewCounter
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal'
    volumes:
      - dynamodb-data:/home/dynamodblocal

volumes:
  dynamodb-data:
